### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.decorators'

### ISSUE THREAD

**Issue by ashabmoaz** [x4nth055/emotion-recognition-using-speech#33] opened 2021-11-02 08:41 UTC
Hi 

First of all, Thanks a lot for providing such a valuable material. I am new to Python and may be its a silly question.

I am trying to run the Speech Emotion Recognition code. I followed all the instructions provided but when I try to run the test.py, it gives me below error.

**ModuleNotFoundError: No module named 'numba.decorators'**

**numba** is already installed, 

any bit of help will be really Appreciated, 

Thanks in advance

**Comment by x4nth055** [comment] 2021-11-13 08:12
Hello @ashabmoaz ,

Thanks for the support. Can you let me know your OS you're currently using? So I can re-produce the error in my side.

Thanks,

**Comment by Berlily** [comment] 2021-11-21 22:02
@x4nth055, I have the same error! And I have numba installed too. My OS is mac OS Big Sur

**Comment by kananmammad** [comment] 2021-12-24 07:31
Hello
@x4nth055, I have the same error. I have installed numba in my Laptop. My OS is Ubuntu 20.04.3 LTS 64 bit

**Comment by sahiljain11** [comment] 2022-01-13 19:48
I had this error and I resolved it by simply updating librosa like follows: `pip3 install --upgrade librosa`

I believe the issue is that the older version of librosa uses a different set of decorators with numba. Hopefully this helps!

**Comment by Berlily** [comment] 2022-01-14 11:54
Thank you very much, Sahil!

чт, 13 янв. 2022 г. в 22:48, Sahil Jain ***@***.***>:

**Comment by x4nth055** [comment] 2022-03-05 09:43
Thanks, @sahiljain11 ,

I wasn't able to identify the issue until you did! I'm closing the issue then.

**Closed by x4nth055** 2022-03-05 09:43 UTC
